apiVersion: v1
kind: Service

metadata:
  name: music-digging-app-service
  namespace: music-digging

spec:
  type: NodePort

  selector:
    app: music-digging-app

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080